version: "3.9"

services:
  db:
    build:
      context: database/
      dockerfile: Dockerfile
    container_name: gpb-test-database
    hostname: database
    ports:
      - "54329:5432"
    volumes:
      - ${PWD}/docker/volumes/postgres@15:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=gpb
      - POSTGRES_USER=gpb
      - POSTGRES_PASSWORD=gpb
      - "DB_URL=file:///tmp/sample.sql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - gpb_local

  api:
    build:
      context: api/
      dockerfile: docker/Dockerfile
    command: python manage.py api dev --host 0 src/api.py
    container_name: gpb-test-api
    hostname: api
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/api:/app
    networks:
      - gpb_local
    depends_on:
      - db

  ui:
    build:
      context: ui/
      dockerfile: docker/Dockerfile
    command: npm start
    container_name: gpb-test-ui
    hostname: ui
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    volumes:
      - ${PWD}/ui:/app
    networks:
      - gpb_local
    depends_on:
      - api

  import:
    build:
      context: import/
      dockerfile: docker/Dockerfile
    command: python manage.py import -f /tmp/sample/out.zip -z -t -d
    container_name: gpb-test-import
    hostname: import
    volumes:
      - ${PWD}/import:/app
      - ${PWD}/sample/:/tmp/sample/
    networks:
      - gpb_local
    depends_on:
      - db


networks:
  gpb_local:
